[package]
name = "adventofcode_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"

[dev-dependencies]
criterion = "0.4"

[lib]
bench = false

[[bin]]
name = "adventofcode_2022"
path = "src/main.rs"
bench = false

[[bench]]
name = "main"
harness = false
